### PR TITLE
Continue on BSON parsing errors if continue_on_error is true.

### PR DESCRIPTION
**Pull request by sha1sum**
BSON parsing errors should not cause critical-level errors if `continue_on_error` is `true`. This PR allows records to continue to be processed on a dump in cases where these parsing errors occur.

### CODE REVIEW

**Comment by behackett** [comment]
What BSON error are you trying to work around?

**Comment by sha1sum** [comment]
@behackett There were a few "Date out of range" `InvalidBSON` errors when attempting to loop through the documents in the cursor.

**Comment by behackett** [comment]
Ah, good old python datetime.datetime, which only accepts years between 1 and 9999. Are you sure you have PyMongo's C extensions installed? Datetime's C API accepts much larger values for year. You can check like this:

python -c "import pymongo; print(pymongo.has_c())"

**Comment by sha1sum** [comment]
That's a `False`. I'll try to see how to get them installed. I'm a golang dev, so Python is not my speciality, and this is an AWS EC2 instance, but I'll see what I can do!

**Comment by behackett** [comment]
There are no pre-compiled binaries for Linux on pypi (it's a long sad story about python packaging that will be fixed soon), so make sure you follow these instructions before reinstalling pymongo:

http://api.mongodb.com/python/current/installation.html#dependencies-for-installing-c-extensions-on-unix

**Comment by sha1sum** [comment]
Opting for a log warning via #505 -- this PR is no longer necessary.

**Pull request closed without merging**
