### PR TITLE
Allow full class path imports with new config arg.

### PR DESCRIPTION
**Pull request by estobbart**
Allows an override on the module loading for a Django style import of the class.

    docManagerClassPath : 'foo.bar.baz.MyDocManager'

### CODE REVIEW

**Comment by aherlihy** [comment]
Hello, thank you for contributing!

Would you mind providing some clarification on what the use case for this is? I'm not sure what Django-style import means. Custom doc managers are already supported by using namespace packaging.

**Comment by estobbart** [comment]
Sorry, should have clarified. This eliminates the need for specific directory layout. While in development you don't need all the quirky import statements in your source package's __init__.py files, or if you've deployed your app the projects can live in their own site-packages space. It also allows you to name the class whatever you want.
This is very similar to how middleware classes are imported in a Django settings file.

**Comment by aherlihy** [comment]
Thank you for contributing!

**Comment by estobbart** [comment]
Is there a repo for the docs where I can write up this solution?

**Comment by aherlihy** [comment]
The only documentation lives in the Github Wiki, which you should be able to edit directly.

**Pull request merged**
