### PR TITLE
support nested properties (fix for oplog field filtering)

### PR DESCRIPTION
**Pull request by robertaistleitner**
this should fix my created ticket #477, which solves issues with nested property updates.

### CODE REVIEW

**Comment by robertaistleitner** [comment]
I have a question regarding test case test_nested_fields, which is not correct in my eyes (assertion error can be found attached). When using nested properties with elasticsearch, you need to define the fields like I did (```{'a.b.c': 2, 'a.e': 5}```), because otherwise existing subproperties will be overridden in elasticsearch. E.g. if you have ```a.c``` with a value of 10, this will be lost. Maybe the behaviour of solr is different here (I'm not using solr at all).

```
FAIL: test_nested_fields (tests.test_filter_fields.TestFilterFields)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/mongodb-labs/mongo-connector/tests/test_filter_fields.py", line 506, in test_nested_fields
    check_nested(document, fields, filtered_document)
  File "/home/travis/build/mongodb-labs/mongo-connector/tests/test_filter_fields.py", line 494, in check_nested
    self.assertEqual(filtered_result, filtered_document)
AssertionError: {'a.e': 5, 'a.b.c': 2} != {'a': {'b': {'c': 2}, 'e': 5}}
- {'a.b.c': 2, 'a.e': 5}
+ {'a': {'b': {'c': 2}, 'e': 5}}
```

**Comment by letsgolesco** [comment]
Question: does this PR cover arrays? 

I've noticed that Mongo Connector misses updates to elements of arrays (whether they're strings or objects).

**Comment by ShaneHarvey** [comment]
@letsgolesco this PR does not cover arrays. Right now the ``fields`` and ``exclude-fields`` options [do not support spanning arrays](https://github.com/mongodb-labs/mongo-connector/blob/2.4.1/mongo_connector/connector.py#L664-L665).

**Comment by ShaneHarvey** [comment]
@robertaistleitner Your pull request looks good. Would you mind adding some tests for $set operations with include fields and exclude fields (similar [``test_nested_fields``](https://github.com/mongodb-labs/mongo-connector/blob/2.4.1/tests/test_filter_fields.py#L485) and [``test_nested_exclude_fields``](https://github.com/mongodb-labs/mongo-connector/blob/2.4.1/tests/test_filter_fields.py#L554)) so we can make sure they work properly?

**Comment by letsgolesco** [comment]
Thanks for the heads up @ShaneHarvey - does that mean edits within arrays would work if the `fields` option is not used?

**Comment by ShaneHarvey** [comment]
Yes, updates to arrays without using ``fields`` work properly.

**Comment by ShaneHarvey** [comment]
@robertaistleitner thanks for your work on this pull request. Your changes will be merged in as part of pull request #534 which implements the remaining improvements on top of yours.

**Pull request closed without merging**
