### PR TITLE
Document Manger for Splunk

### PR DESCRIPTION
**Pull request by asifhj**
Hereby I am pushing document manager code for Splunk. I have tested it and running in my environment.

### CODE REVIEW

**Comment by llvtt** [comment]
@asifhj 
This is wonderful! Thanks for making this. Probably the best way to publish this document manager is to put it in its own Python package. This offers a number of advantages:

1. You won't have to make more pull requests to make changes/additional versions of your DM.
2. You can write your own README and documentation on your DM's github page.
3. Issues and pull requests against your DM can be tracked separately from issues against MC itself.

There are instructions for how to do this [here](https://github.com/10gen-labs/mongo-connector/wiki/Writing%20Your%20Own%20DocManager#step-2-distribute-your-docmanager). Please let me know if there's anything I can do to support this.

I'll also start a "List of DocManagers for Mongo Connector" in the wiki or REAMDE that will point to your project.

**Comment by aherlihy** [comment]
Hello @asifhj did you ever publish the Splunk doc manager?

**Comment by asifhj** [comment]
I did not publish can you help me to publish this doc manager.

**Comment by aherlihy** [comment]
Yes, what do you need help with?

In my opinion the most difficult part of publishing a separate doc manager is the namespace packaging, but you should just copy the elastic doc manager's package layout and setup.py.

There is also a wiki page for writing your own doc manager, https://github.com/mongodb-labs/mongo-connector/wiki/Writing-Your-Own-DocManager which should help with any implementation details.

**Comment by ShaneHarvey** [comment]
Closing this because any new doc managers should be packaged separately.

**Pull request closed without merging**
